name: Docker Image
on:
  workflow_run:
    workflows: ["CI DevOps 2024"]
    types: completed # Triggers only when the triggering workflow has completed

jobs:
  # Define job to build and publish docker image
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Trigger only on success
    runs-on: ubuntu-22.04
    
    # Steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
           # Relative path to the place where source code with Dockerfile is located
           context: ./simple-api
           # Note: tags has to be all lower-case
           tags:  ${{secrets.DOCKER_USERNAME}}/tp-devops-simple-api:backend
           # Build on feature branches, push only on main branch
           push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
           # Relative path to the place where source code with Dockerfile is located
           context: ./database
           # Note: tags has to be all lower-case
           tags:  ${{secrets.DOCKER_USERNAME}}/tp-devops-simple-api:database
           # Build on feature branches, push only on main branch
           push: ${{ github.ref == 'refs/heads/main' }}
    
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
           # Relative path to the place where source code with Dockerfile is located
           context: ./http-server
           # Note: tags has to be all lower-case
           tags:  ${{secrets.DOCKER_USERNAME}}/tp-devops-simple-api:httpd
           # Build on feature branches, push only on main branch
           push: ${{ github.ref == 'refs/heads/main' }}

      - name: Clear Docker Credentials
        run: |
          docker logout
